// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: window.proto

package windowpost

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 注册window worker
type WindowWorkerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerAddr string `protobuf:"bytes,1,opt,name=WorkerAddr,proto3" json:"WorkerAddr,omitempty"`
}

func (x *WindowWorkerRequest) Reset() {
	*x = WindowWorkerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_window_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WindowWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowWorkerRequest) ProtoMessage() {}

func (x *WindowWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_window_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowWorkerRequest.ProtoReflect.Descriptor instead.
func (*WindowWorkerRequest) Descriptor() ([]byte, []int) {
	return file_window_proto_rawDescGZIP(), []int{0}
}

func (x *WindowWorkerRequest) GetWorkerAddr() string {
	if x != nil {
		return x.WorkerAddr
	}
	return ""
}

type WindowWorkerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *WindowWorkerResponse) Reset() {
	*x = WindowWorkerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_window_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WindowWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowWorkerResponse) ProtoMessage() {}

func (x *WindowWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_window_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowWorkerResponse.ProtoReflect.Descriptor instead.
func (*WindowWorkerResponse) Descriptor() ([]byte, []int) {
	return file_window_proto_rawDescGZIP(), []int{1}
}

func (x *WindowWorkerResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 释放client
type ReleaseClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientAddr string `protobuf:"bytes,1,opt,name=ClientAddr,proto3" json:"ClientAddr,omitempty"`
}

func (x *ReleaseClientRequest) Reset() {
	*x = ReleaseClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_window_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReleaseClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseClientRequest) ProtoMessage() {}

func (x *ReleaseClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_window_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseClientRequest.ProtoReflect.Descriptor instead.
func (*ReleaseClientRequest) Descriptor() ([]byte, []int) {
	return file_window_proto_rawDescGZIP(), []int{2}
}

func (x *ReleaseClientRequest) GetClientAddr() string {
	if x != nil {
		return x.ClientAddr
	}
	return ""
}

type ReleaseClientResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReleaseClientResponse) Reset() {
	*x = ReleaseClientResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_window_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReleaseClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseClientResponse) ProtoMessage() {}

func (x *ReleaseClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_window_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseClientResponse.ProtoReflect.Descriptor instead.
func (*ReleaseClientResponse) Descriptor() ([]byte, []int) {
	return file_window_proto_rawDescGZIP(), []int{3}
}

// 可用的client
type FreeClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FreeClientRequest) Reset() {
	*x = FreeClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_window_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FreeClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreeClientRequest) ProtoMessage() {}

func (x *FreeClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_window_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreeClientRequest.ProtoReflect.Descriptor instead.
func (*FreeClientRequest) Descriptor() ([]byte, []int) {
	return file_window_proto_rawDescGZIP(), []int{4}
}

type FreeClientResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientAddr string `protobuf:"bytes,1,opt,name=ClientAddr,proto3" json:"ClientAddr,omitempty"`
}

func (x *FreeClientResponse) Reset() {
	*x = FreeClientResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_window_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FreeClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreeClientResponse) ProtoMessage() {}

func (x *FreeClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_window_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreeClientResponse.ProtoReflect.Descriptor instead.
func (*FreeClientResponse) Descriptor() ([]byte, []int) {
	return file_window_proto_rawDescGZIP(), []int{5}
}

func (x *FreeClientResponse) GetClientAddr() string {
	if x != nil {
		return x.ClientAddr
	}
	return ""
}

// 分配计算任务
type TaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinerID     uint64 `protobuf:"varint,1,opt,name=MinerID,proto3" json:"MinerID,omitempty"`
	Privsectors []byte `protobuf:"bytes,2,opt,name=Privsectors,proto3" json:"Privsectors,omitempty"`
	Random      []byte `protobuf:"bytes,3,opt,name=Random,proto3" json:"Random,omitempty"`
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_window_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_window_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_window_proto_rawDescGZIP(), []int{6}
}

func (x *TaskRequest) GetMinerID() uint64 {
	if x != nil {
		return x.MinerID
	}
	return 0
}

func (x *TaskRequest) GetPrivsectors() []byte {
	if x != nil {
		return x.Privsectors
	}
	return nil
}

func (x *TaskRequest) GetRandom() []byte {
	if x != nil {
		return x.Random
	}
	return nil
}

type PoStProof struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PoStProof  int64  `protobuf:"varint,1,opt,name=PoStProof,proto3" json:"PoStProof,omitempty"`
	ProofBytes []byte `protobuf:"bytes,2,opt,name=ProofBytes,proto3" json:"ProofBytes,omitempty"`
}

func (x *PoStProof) Reset() {
	*x = PoStProof{}
	if protoimpl.UnsafeEnabled {
		mi := &file_window_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoStProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoStProof) ProtoMessage() {}

func (x *PoStProof) ProtoReflect() protoreflect.Message {
	mi := &file_window_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoStProof.ProtoReflect.Descriptor instead.
func (*PoStProof) Descriptor() ([]byte, []int) {
	return file_window_proto_rawDescGZIP(), []int{7}
}

func (x *PoStProof) GetPoStProof() int64 {
	if x != nil {
		return x.PoStProof
	}
	return 0
}

func (x *PoStProof) GetProofBytes() []byte {
	if x != nil {
		return x.ProofBytes
	}
	return nil
}

type TaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status       string       `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	SectorNumber []uint64     `protobuf:"varint,2,rep,packed,name=SectorNumber,proto3" json:"SectorNumber,omitempty"`
	Proofs       []*PoStProof `protobuf:"bytes,3,rep,name=Proofs,proto3" json:"Proofs,omitempty"`
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_window_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_window_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_window_proto_rawDescGZIP(), []int{8}
}

func (x *TaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskResponse) GetSectorNumber() []uint64 {
	if x != nil {
		return x.SectorNumber
	}
	return nil
}

func (x *TaskResponse) GetProofs() []*PoStProof {
	if x != nil {
		return x.Proofs
	}
	return nil
}

// 心跳
type HeartBeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SentTime int64 `protobuf:"varint,1,opt,name=SentTime,proto3" json:"SentTime,omitempty"`
}

func (x *HeartBeatRequest) Reset() {
	*x = HeartBeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_window_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatRequest) ProtoMessage() {}

func (x *HeartBeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_window_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatRequest.ProtoReflect.Descriptor instead.
func (*HeartBeatRequest) Descriptor() ([]byte, []int) {
	return file_window_proto_rawDescGZIP(), []int{9}
}

func (x *HeartBeatRequest) GetSentTime() int64 {
	if x != nil {
		return x.SentTime
	}
	return 0
}

type HeartBeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *HeartBeatResponse) Reset() {
	*x = HeartBeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_window_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatResponse) ProtoMessage() {}

func (x *HeartBeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_window_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatResponse.ProtoReflect.Descriptor instead.
func (*HeartBeatResponse) Descriptor() ([]byte, []int) {
	return file_window_proto_rawDescGZIP(), []int{10}
}

func (x *HeartBeatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// ServerInfo
type ServerInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ServerInfoRequest) Reset() {
	*x = ServerInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_window_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoRequest) ProtoMessage() {}

func (x *ServerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_window_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoRequest.ProtoReflect.Descriptor instead.
func (*ServerInfoRequest) Descriptor() ([]byte, []int) {
	return file_window_proto_rawDescGZIP(), []int{11}
}

type ServerInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info map[string]*ClientInfo `protobuf:"bytes,1,rep,name=Info,proto3" json:"Info,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ServerInfoResponse) Reset() {
	*x = ServerInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_window_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoResponse) ProtoMessage() {}

func (x *ServerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_window_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoResponse.ProtoReflect.Descriptor instead.
func (*ServerInfoResponse) Descriptor() ([]byte, []int) {
	return file_window_proto_rawDescGZIP(), []int{12}
}

func (x *ServerInfoResponse) GetInfo() map[string]*ClientInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type ClientInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientAddr string `protobuf:"bytes,1,opt,name=ClientAddr,proto3" json:"ClientAddr,omitempty"`
	Busy       bool   `protobuf:"varint,2,opt,name=Busy,proto3" json:"Busy,omitempty"`
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_window_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_window_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_window_proto_rawDescGZIP(), []int{13}
}

func (x *ClientInfo) GetClientAddr() string {
	if x != nil {
		return x.ClientAddr
	}
	return ""
}

func (x *ClientInfo) GetBusy() bool {
	if x != nil {
		return x.Busy
	}
	return false
}

var File_window_proto protoreflect.FileDescriptor

var file_window_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x70, 0x6f, 0x73, 0x74, 0x22, 0x35, 0x0a, 0x13, 0x57, 0x69,
	0x6e, 0x64, 0x6f, 0x77, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x41, 0x64, 0x64,
	0x72, 0x22, 0x2e, 0x0a, 0x14, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x57, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x36, 0x0a, 0x14, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72, 0x22, 0x17, 0x0a, 0x15, 0x52, 0x65, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x46, 0x72, 0x65, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x34, 0x0a, 0x12, 0x46, 0x72, 0x65, 0x65, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72, 0x22, 0x61, 0x0a,
	0x0b, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x4d, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x4d,
	0x69, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x72, 0x69, 0x76, 0x73, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x50, 0x72, 0x69,
	0x76, 0x73, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x61, 0x6e, 0x64,
	0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d,
	0x22, 0x49, 0x0a, 0x09, 0x50, 0x6f, 0x53, 0x74, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x1c, 0x0a,
	0x09, 0x50, 0x6f, 0x53, 0x74, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x50, 0x6f, 0x53, 0x74, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x1e, 0x0a, 0x0a, 0x50,
	0x72, 0x6f, 0x6f, 0x66, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0a, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0x79, 0x0a, 0x0c, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x53, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x0c, 0x53, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2d, 0x0a, 0x06, 0x50, 0x72, 0x6f, 0x6f, 0x66,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77,
	0x70, 0x6f, 0x73, 0x74, 0x2e, 0x50, 0x6f, 0x53, 0x74, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x52, 0x06,
	0x50, 0x72, 0x6f, 0x6f, 0x66, 0x73, 0x22, 0x2e, 0x0a, 0x10, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42,
	0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65,
	0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x53, 0x65,
	0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x2b, 0x0a, 0x11, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42,
	0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x13, 0x0a, 0x11, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xa3, 0x01, 0x0a, 0x12, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3c, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e,
	0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49, 0x6e,
	0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x4f, 0x0a,
	0x09, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2c, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x77, 0x69,
	0x6e, 0x64, 0x6f, 0x77, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x40,
	0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x42, 0x75, 0x73, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x42, 0x75, 0x73, 0x79,
	0x32, 0xe2, 0x03, 0x0a, 0x0a, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x47, 0x72, 0x70, 0x63, 0x12,
	0x53, 0x0a, 0x0e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x57, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x12, 0x1f, 0x2e, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x57,
	0x69, 0x6e, 0x64, 0x6f, 0x77, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x70, 0x6f, 0x73, 0x74, 0x2e,
	0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0c, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65,
	0x54, 0x61, 0x73, 0x6b, 0x12, 0x17, 0x2e, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x70, 0x6f, 0x73,
	0x74, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x42, 0x65, 0x61, 0x74, 0x12, 0x1c, 0x2e, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x70, 0x6f, 0x73,
	0x74, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x70, 0x6f, 0x73, 0x74, 0x2e,
	0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4e, 0x0a, 0x0d, 0x43, 0x61, 0x6e, 0x55, 0x73, 0x65, 0x64, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x12, 0x1d, 0x2e, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x70, 0x6f, 0x73, 0x74, 0x2e,
	0x46, 0x72, 0x65, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1e, 0x2e, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x46,
	0x72, 0x65, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x54, 0x0a, 0x0d, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x12, 0x20, 0x2e, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x70, 0x6f, 0x73, 0x74, 0x2e,
	0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x70, 0x6f, 0x73,
	0x74, 0x2e, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x0b, 0x57, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x2e, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x70,
	0x6f, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x70, 0x6f,
	0x73, 0x74, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x3b, 0x77, 0x69, 0x6e, 0x64, 0x6f,
	0x77, 0x70, 0x6f, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_window_proto_rawDescOnce sync.Once
	file_window_proto_rawDescData = file_window_proto_rawDesc
)

func file_window_proto_rawDescGZIP() []byte {
	file_window_proto_rawDescOnce.Do(func() {
		file_window_proto_rawDescData = protoimpl.X.CompressGZIP(file_window_proto_rawDescData)
	})
	return file_window_proto_rawDescData
}

var file_window_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_window_proto_goTypes = []interface{}{
	(*WindowWorkerRequest)(nil),   // 0: windowpost.WindowWorkerRequest
	(*WindowWorkerResponse)(nil),  // 1: windowpost.WindowWorkerResponse
	(*ReleaseClientRequest)(nil),  // 2: windowpost.ReleaseClientRequest
	(*ReleaseClientResponse)(nil), // 3: windowpost.ReleaseClientResponse
	(*FreeClientRequest)(nil),     // 4: windowpost.FreeClientRequest
	(*FreeClientResponse)(nil),    // 5: windowpost.FreeClientResponse
	(*TaskRequest)(nil),           // 6: windowpost.TaskRequest
	(*PoStProof)(nil),             // 7: windowpost.PoStProof
	(*TaskResponse)(nil),          // 8: windowpost.TaskResponse
	(*HeartBeatRequest)(nil),      // 9: windowpost.HeartBeatRequest
	(*HeartBeatResponse)(nil),     // 10: windowpost.HeartBeatResponse
	(*ServerInfoRequest)(nil),     // 11: windowpost.ServerInfoRequest
	(*ServerInfoResponse)(nil),    // 12: windowpost.ServerInfoResponse
	(*ClientInfo)(nil),            // 13: windowpost.ClientInfo
	nil,                           // 14: windowpost.ServerInfoResponse.InfoEntry
}
var file_window_proto_depIdxs = []int32{
	7,  // 0: windowpost.TaskResponse.Proofs:type_name -> windowpost.PoStProof
	14, // 1: windowpost.ServerInfoResponse.Info:type_name -> windowpost.ServerInfoResponse.InfoEntry
	13, // 2: windowpost.ServerInfoResponse.InfoEntry.value:type_name -> windowpost.ClientInfo
	0,  // 3: windowpost.WindowGrpc.RegisterWorker:input_type -> windowpost.WindowWorkerRequest
	6,  // 4: windowpost.WindowGrpc.AllocateTask:input_type -> windowpost.TaskRequest
	9,  // 5: windowpost.WindowGrpc.HeartBeat:input_type -> windowpost.HeartBeatRequest
	4,  // 6: windowpost.WindowGrpc.CanUsedClient:input_type -> windowpost.FreeClientRequest
	2,  // 7: windowpost.WindowGrpc.ReleaseClient:input_type -> windowpost.ReleaseClientRequest
	11, // 8: windowpost.WindowGrpc.WorkersInfo:input_type -> windowpost.ServerInfoRequest
	1,  // 9: windowpost.WindowGrpc.RegisterWorker:output_type -> windowpost.WindowWorkerResponse
	8,  // 10: windowpost.WindowGrpc.AllocateTask:output_type -> windowpost.TaskResponse
	10, // 11: windowpost.WindowGrpc.HeartBeat:output_type -> windowpost.HeartBeatResponse
	5,  // 12: windowpost.WindowGrpc.CanUsedClient:output_type -> windowpost.FreeClientResponse
	3,  // 13: windowpost.WindowGrpc.ReleaseClient:output_type -> windowpost.ReleaseClientResponse
	12, // 14: windowpost.WindowGrpc.WorkersInfo:output_type -> windowpost.ServerInfoResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_window_proto_init() }
func file_window_proto_init() {
	if File_window_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_window_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WindowWorkerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_window_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WindowWorkerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_window_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReleaseClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_window_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReleaseClientResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_window_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FreeClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_window_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FreeClientResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_window_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_window_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoStProof); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_window_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_window_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_window_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_window_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_window_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_window_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_window_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_window_proto_goTypes,
		DependencyIndexes: file_window_proto_depIdxs,
		MessageInfos:      file_window_proto_msgTypes,
	}.Build()
	File_window_proto = out.File
	file_window_proto_rawDesc = nil
	file_window_proto_goTypes = nil
	file_window_proto_depIdxs = nil
}
